name: Test item exporting
on:
  workflow_dispatch:
  schedule:
    - cron:  "0 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package
      - name: Run it!
        run: java -jar target/SFExporter.jar
      - name: 'It failed :( notify me'
        if: failure()
        run: 'curl -X POST -H "User-Agent: Mozilla/5.0 (github.com/WalshyDev/SFItemsExporter)" -H "Content-Type: application/json" -d ''{"content": "Failed to update SF items, a breaking update happened! Fix me pls"}'' ${{ secrets.DISCORD_WEBHOOK }}'
